@startuml
class BankAccount {
-private String titular
-private double amount
BankAccount()
+public void deposit(double amount)
+public void withdraw(double amount)
+public String getTitular()
+public void setTitular(String titularX)
+public double getAmount()
+public void setAmount(double amountX)
}
@enduml